In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
import numpy as np
import cv2

In [16]:
# Đường dẫn mới tới thư mục dữ liệu
path_dataset = r"D:\HCSDLDPT\HCSDLDPT_birds_classification\Bird_dataset_OZ_1"
# Đặt biến 'dir' và 'datadir' bằng đường dẫn mới
dir = path_dataset
datadir = path_dataset

In [17]:
Categories = []
# Duyệt qua danh sách các thư mục (lớp) trong datadir (đường dẫn đến dữ liệu hình ảnh), và thêm tên của mỗi thư mục vào danh sách Categories.
for cat in os.listdir(datadir):
    Categories.append(cat)
Categories

['ABBOTTS BABBLER',
 'AFRICAN FIREFINCH',
 'ALBERTS TOWHEE',
 'AMERICAN AVOCET',
 'AMERICAN PIPIT',
 'AMERICAN REDSTART',
 'AMERICAN ROBIN',
 'ANDEAN LAPWING',
 'BANDED PITA',
 'BLACK THROATED WARBLER',
 'BLOOD PHEASANT',
 'CAPE GLOSSY STARLING',
 'CEDAR WAXWING',
 'EASTERN BLUEBIRD',
 'GOLDEN PIPIT',
 'GREEN BROADBILL',
 'HAWFINCH',
 'HIMALAYAN BLUETAIL',
 'HOOPOES',
 'HOUSE FINCH',
 'INDIAN PITTA',
 'IWI',
 'LARK BUNTING',
 'LESSER ADJUTANT',
 'MYNA',
 'NORTHERN PARULA',
 'OCELLATED TURKEY',
 'ORANGE BREASTED TROGON',
 'ORANGE BRESTED BUNTING',
 'OSPREY',
 'OSTRICH',
 'OVENBIRD',
 'OYSTER CATCHER',
 'PAINTED BUNTING',
 'PALILA',
 'PARUS MAJOR',
 'PATAGONIAN SIERRA FINCH',
 'PEACOCK',
 'PEREGRINE FALCON',
 'PHAINOPEPLA',
 'PURPLE FINCH',
 'PURPLE MARTIN',
 'PYGMY KINGFISHER',
 'PYRRHULOXIA',
 'RAINBOW LORIKEET',
 'RAZORBILL',
 'RED BELLIED PITTA',
 'RED CROSSBILL',
 'RED FACED WARBLER',
 'RED FODY',
 'RED HEADED WOODPECKER',
 'RED LEGGED HONEYCREEPER',
 'RED SHOULDERED HAWK',
 'RED WI

In [18]:
bird_data = []
# img_size = (224, 224)
count=0
for cat in Categories:
    path = os.path.join(datadir, cat)
    class_num = Categories.index(cat)
    for img in os.listdir(path):
        img_array = cv2.imread(os.path.join(path, img), cv2.COLOR_BGR2RGB)
        # img_array = cv2.resize(img_array, img_size)
        bird_data.append([ class_num,img_array])
        print(count, end=" ")
        count=count+1

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 

In [19]:
X = []
y = []
for img, label in bird_data:
    y.append(img)
    X.append(label)
# print(X) ma trận
print(y)

[0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 13, 13, 14, 15, 15, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 24, 24, 24, 24, 25, 25, 25, 26, 27, 28, 28, 28, 29, 29, 29, 29, 30, 30, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 34, 34, 34, 34, 35, 35, 36, 36, 36, 37, 38, 38, 38, 38, 39, 40, 40, 40, 41, 42, 42, 42, 42, 43, 43, 43, 44, 44, 45, 46, 46, 47, 48, 48, 48, 48, 49, 50, 50, 51, 51, 51, 52, 53, 53, 53, 54, 55, 56, 56, 56, 56, 57, 58, 58]


In [20]:
#save bird data npy.
np.save("bird_data.npy", np.array(bird_data, dtype=object))

In [21]:
def rgb_to_hsv(pixel):
    r , g, b = pixel 
    r , g ,b = b / 255.0, g / 255.0, r / 255.0
    
    v = max(r,g,b)
    delta = v - min(r,g,b)
    
    if delta == 0:
        h = 0
        s = 0
    else:
        s = delta / v
        if r == v:
            h = (g - b) / delta
        elif g == v:
            h = 2 + (b - r) / delta
        else:
            h = 4 + (r - g) / delta
        h = (h / 6) % 1.0
        
    return [int(h*180), int(s*255), int(v*255)]

def covert_image_rgb_to_hsv(img):
  hsv_image=[]
  for i in img:
    hsv_image2=[]
    for j in i:
      new_color=rgb_to_hsv(j)
      hsv_image2.append((new_color))
    hsv_image.append(hsv_image2)
  hsv_image=np.array(hsv_image)
  return hsv_image

def my_calcHist(image, channels, histSize, ranges):
    # Khởi tạo histogram với tất cả giá trị bằng 0
    hist = np.zeros(histSize, dtype=np.int64)
    # Lặp qua tất cả các pixel trong ảnh
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            # Lấy giá trị của kênh màu được chỉ định
            bin_vals = [image[i, j, c] for c in channels]
            # Tính chỉ số của bin
            bin_idxs = [(bin_vals[c] - ranges[c][0]) * histSize[c] // (ranges[c][1] - ranges[c][0]) for c in range(len(channels))]
            # Tăng giá trị của bin tương ứng lên 1
            hist[tuple(bin_idxs)] += 1
    return hist

In [22]:
from tqdm import tqdm
data_bird_RGB =[]
for i in range(len(bird_data)):
  # Đọc ảnh và chuyển đổi sang không gian màu HSV
  img = bird_data[i][1]
  bins = [8, 8,8]
  ranges = [[0, 256], [0, 256], [0, 256]]
  # img_hsv=covert_image_rgb_to_hsv(img)
  hist_my = my_calcHist(img, [0, 1, 2], bins, ranges)
  embedding_bird = hist_my.flatten()
  embedding_bird[0]=0
  data_bird_RGB.append([bird_data[i][0],embedding_bird])
  print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 

KeyboardInterrupt: 

In [ ]:
embedding_bird

array([   0,  124,   24,    2,    8,    4,    2,    0,   20,   93,   58,
         65,   74,  118,   35,   28,    0,    0,    4,   22,   50,  263,
         78,   69,    0,    0,    0,    0,    3,  328,  687,  194,    0,
          0,    0,    0,    0,  195, 2946, 1087,    0,    0,    0,    0,
          0,    0,   54, 1003,    0,    0,    0,    0,    0,    0,    0,
         27,    0,    0,    0,    0,    0,    0,    0,    0,    8,   21,
          5,    0,    0,    0,    0,    0,   40,  328,  466,  228,   73,
         27,   19,    1,    0,    8,   48,  157,  160,  290,  243,  215,
          0,    0,    0,   17,   48,   88,  117,  272,    0,    0,    0,
          0,    6,  155,  293,  140,    0,    0,    0,    0,    0,    2,
         44,  209,    0,    0,    0,    0,    0,    0,    1,  101,    0,
          0,    0,    0,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,   21,  207,   58,   38,    1,    1,
          0,    0,   15,  171,  217,  276,  231,  1

In [ ]:
data_bird_RGB

[[0,
  array([   0,  854,  100,    0,    0,    0,    0,    0,    1,  123,  278,
            0,    0,    0,    0,    0,    0,    0,   10,    1,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,   11,   37,
            4,    0,    0,    0,    0,    0,    0,  179,  960,  117,    0,
            0,    0,    0,    0,    0,  172,  293,    1,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    1,   54,    7,    0,    0,    0,
            0,    0,

In [ ]:
np.save("bird_RGB.npy", np.array(data_bird_RGB, dtype=object))

In [ ]:
data_bird_HSV=[]
for i in range(len(bird_data)) :
  # Đọc ảnh và chuyển đổi sang không gian màu HSV
  img = bird_data[i][1]
  bins = [8,12,3]
  ranges = [[0, 180], [0, 256], [0, 256]]
  img_hsv=covert_image_rgb_to_hsv(img)
  hist_my = my_calcHist(img_hsv, [0, 1, 2], bins, ranges)
  # print(hist_my.shape)
  embedding = hist_my.flatten()
  embedding[0]=0
  data_bird_HSV.append([bird_data[i][0],embedding])
  print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 

KeyboardInterrupt: 

In [ ]:
embedding

array([   0,    6,    4,   42,   26,   14,   83,   27,  113,   85,   93,
        226,   87,  158,  267,   88,  265,  474,   45,  399,  768,   46,
        275,  907,   30,  190, 1052,   13,  152, 1272,   14,  139, 1409,
         12,  122, 5733,   17,    3,    0,   47,    1,    2,   22,    0,
          3,   31,    0,    2,   23,    0,    1,   48,    5,    1,   22,
         17,   11,    8,   12,   69,    2,    1,   72,    0,    0,   43,
          0,    0,   32,    3,    0,    4,   17,    1,    0,   36,    1,
          0,   27,    0,    0,   11,    0,    0,    4,    0,    0,    4,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,   15,    0,    0,   15,    1,
          0,   74,    1,    0,   90,    0,    0,   39,    0,    0,    6,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    6,    0,    0,   32,    2,    0,   

In [ ]:
data_bird_HSV

[[0,
  array([   0,   68,  106,   22,  578,  398,   50, 1798,  885,   97, 1589,
          446,  203, 1233,   95,  300,  582,    0,  344,  183,    0,  325,
           59,    0,  317,   17,    0,  297,    3,    0,  208,    0,    0,
         1401,    0,    0,    6,    7,    7,   20,    4,    0,   23,    1,
            0,   20,    2,    0,   19,    0,    0,   22,    0,    0,   17,
            0,    0,   19,    0,    0,    7,    0,    0,   11,    0,    0,
            2,    0,    0,   63,    0,    0,    0,    1,    1,    0,    0,
            0,    3,    0,    0,    6,    0,    0,    3,    0,    0,   12,
            0,    0,    1,    0,    0,   13,    0,    0,    7,    0,    0,
            4,    0,    0,    1,    0,    0,  926,    0,    0,    0,    3,
            2,    6,    0,    0,    8,    0,    0,   19,    0,    0,   10,
            0,    0,   19,    0,    0,    1,    0,    0,   17,    0,    0,
            1,    0,    0,    1,    0,    0,    4,    0,    0,   43,    0,
            0,    0,

In [ ]:
np.save("bird_HSV.npy", np.array(data_bird_HSV, dtype=object))

In [ ]:
from skimage import exposure
from skimage import feature
import cv2
def convert_image_rgb_to_gray(img_rgb, resize="no"):
  h, w, _ = img_rgb.shape
  # Create a new grayscale image with the same height and width as the RGB image
  img_gray = np.zeros((h, w), dtype=np.uint32)

  # Convert each pixel from RGB to grayscale using the formula Y = 0.299R + 0.587G + 0.114B
  for i in range(h):
      for j in range(w):
          r, g, b = img_rgb[i, j]
          gray_value = int(0.299*r + 0.587*g + 0.114*b)
          img_gray[i, j] = gray_value
  # print(gray_image.shape())
  if resize!="no":
     img_gray = cv2.resize(src=img_gray, dsize=(496, 496))
  return np.array(img_gray)
def hog_feature(gray_img):# default gray_image
  # 1. Khai báo các tham số
  (hog_feats, hogImage) = feature.hog(gray_img, orientations=9, pixels_per_cell=(8 , 8),
    cells_per_block=(2,2), transform_sqrt=True, block_norm="L2",
    visualize=True)
  return hog_feats

In [ ]:
data_bird_HOG=[]
for i in range(len(bird_data)) :
  # Đọc ảnh và chuyển đổi sang không gian màu HSV

  # img_hsv=covert_image_rgb_to_hsv(img)
  # hist_my = my_calcHist(img_hsv, [0, 1, 2], bins, ranges)
  # print(hist_my.shape)
  img_gray=convert_image_rgb_to_gray(bird_data[i][1])
  embedding = hog_feature(img_gray)
  embedding = embedding.flatten()
  # embedding[0]=0
  data_bird_HOG.append([bird_data[i][0],embedding])
  print(i,end=' ')

NameError: name 'bird_data' is not defined

In [ ]:
embedding

In [ ]:
data_bird_HOG

In [ ]:
np.save("bird_HOG.npy",data_bird_HOG)